server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/interview"
    username: postgres
    password: developer
    hikari:
      schema: test
